Improve dotfiles script error-handling

diff --git a/dotfiles b/dotfiles
--- a/dotfiles
+++ b/dotfiles
@@ -1,23 +1,39 @@
 #!/usr/bin/env bash
 
+# dotfiles: Install or update dotfiles
+
+PROGRAM_NAME="$(basename "$0")"
+
+# Displays help text
+print_help () {
+    echo "$PROGRAM_NAME - Usage:"
+    echo "    $PROGRAM_NAME --help                            Display this help message."
+    echo "    $PROGRAM_NAME --tag <tag> --file <file>         Install dotfiles under <tag> in <file>."
+}
+
+if [[ $# -eq 0 ]]; then
+    print_help
+    exit
+fi
+
 # Parse given arguments
 while [[ $# -gt 0 ]];  do
     case $1 in
-        -f | --file) file="$2" ;;
-        -t | --tag) tag="$2" ;;
-        -h | --help)
-            echo "Usage:"
-            echo "    dotfiles.sh --help                            Display this help message."
-            echo "    dotfiles.sh --tag <tag> --file <file>         Install dotfiles under <tag> in <file>."
-            exit 0 ;;
+        -f | --file)    file="$2"
+                        ;;
+        -t | --tag)     tag="$2"
+                        ;;
+        -h | --help)    print_help
+                        exit 0
+                        ;;
     esac
-shift
+    shift
 done
 
 # Check given file exists
 if [[ ! -f "$file" ]];  then
     tput setaf 1; # 1 - red
-    echo "Error: File not found: '$file'."
+    echo "$PROGRAM_NAME: File not found: '$file'." >&2
     tput sgr0 # reset
     exit 1
 fi
@@ -40,7 +56,7 @@ while read line || [[ -n "$line" ]];  do
         # Check target exists
         if [[ ! -f "$target" ]];  then
             tput setaf 1; # 1 - red
-            echo "Error: Target not found: '$target'."
+            echo "$PROGRAM_NAME: Target not found: '$target'." >&2
             tput sgr0 # reset
             exit 2
         fi
